# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7827014fadc06970a73da4648a28a7e39b6015589d6dfbd5d104c925cda9e76e7803e93c7c83f3bc1241ded02ca7d5f67633b1f57a9fa445fbc47573591677b9

test:
  secret_key_base: ad12db487a3c6a918a58428a7b5117244eed449aa1cf88746f95ddab4c7407046f3f0f52ea367b53cc7529d70803f475f0202b2d3c87a641ea001272f5dc36f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
